services:
  appsS:
    image: skyhas/starter-express:latest
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT} 
    env_file:
      - .env
    networks:
      - docker_default

networks:
  docker_default:
    external: true
